### ISSUE TITLE
Extract number of comments of an app weekly and monthly

### ISSUE THREAD

**Issue by charlypa** [aicore/app_info_extracter#3]
Add support to extract how many comments happening for an app in a week and month.
1. Add a configuration in config.yaml  to enable this feature
2. It would be better to add this configuration along with this feature https://github.com/aicore/app_info_extracter/issues/1

**Comment by charlypa** [comment]
if you see the files generated there is a field called at in csv
You could sort data based on that field and get the relevant information
There are two ways to do it
1. Dump all the recent information and do the sorting and classification based on the time line
2.  Run the utility weekly or monthly and store the information some where and extract the results.

I would say option 1 is easy to implement
second one is slightly complex as it require caching filtering and merging of data
You can define week as  data for   (rundate -7days*i) i = 1,2....n
where n is ideally the release date of an app
However it is hard to crawl that deep with current set up
for month you can do (rundate -30days*i) where i = 1, 2,...n

**Comment by dhruvpeter** [comment]
Pull request: #16 

To enable counting reviews in a month, `count_reviews_monthly `in `config_yaml `should store "yes".
To enable counting reviews in a week, `count_reviews_weekly `in `config_yaml `should store "yes".
The result will be stored as csv files in the corresponding app's directory.

**Comment by dhruvpeter** [comment]
### Finding the number of reviews in each month
Sorted the dataframe containing reviews with 'at' field which contains the date at time at which review is made. Then grouped the dataframe on year and month in 'at' and took count of each group which contains the number of reviews made in each month. Made a list of the count and another list of distinct months from the sorted dataframe. Combined both of the list to make a new dataframe with 'month' and 'no_of_reviews' as columns. 


### Finding the number of reviews in each week
Sorted the dataframe containing reviews with 'at' field which contains the date at time at which review is made. Then grouped each week in the 'at' field. Appended the week name to a list and took the length of each group which gave the count and appended it to another list. Finally created a dataframe with the two list with columns 'week' and 'no_of_reviews'.
