### ISSUE TITLE
Create CLI and readme file

### ISSUE THREAD

**Issue by abose** [aicore/app_info_extracter#8]
- [x] Read about [building delightful CLIs](https://blog.developer.atlassian.com/10-design-principles-for-delightful-clis/)
- [x] Define CLI UX (commands, args, help Etc.) 
- [x] Help for CLI
- [x] Update readme.md file with CLI syntax.

**Comment by abose** [comment]
Pull req: https://github.com/aicore/app_info_extracter/pull/10

**Comment by dhruvpeter** [comment]
Made changes in `main.py` to support CLI.

Program can now be run using `python main.py config.yaml`
config.yaml is provided as command line input which contains the configurations of the apps.
To see usage and description, type `python main.py -h` or `python main.py --help` in terminal.

### Sample input and output of CLI

Input: `python main.py -h`

Output:
usage: `python main.py <file> `

Description:
App info extractor is a utility to extract and analyze customer reviews and critical metrics of apps from multiple   
sources like google play store, Apple play store, and anyother sources.This utility is highly configurable to extract
and give relevant information about any app in a meaningful way.

positional arguments:
  file        `config.yaml` file containing the configuration for each app

optional arguments:
  `-h`, `--help`  show this help message and exit
